
services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend:/app
      - ./certs:/app/certs
    depends_on:
      - db
      - redis
    restart: always
    command: >
      sh -c "/wait-for-it.sh db:5432 --timeout=30 --strict -- uvicorn app.main:app --host 0.0.0.0 --port 8000 --ssl-keyfile=/app/certs/localhost+2-key.pem --ssl-certfile=/app/certs/localhost+2.pem --reload"


  
  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules 
      - ./certs:/app/certs
    depends_on:
      - backend
    restart: always
  
volumes:
  postgres_data:
